<a href="https://colab.research.google.com/github/RaoUmair98/All-Type-Of-Tasks/blob/main/Word_Embedding_Using_Keras_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000


In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)


[[3497, 5757, 3254, 8472], [3497, 5757, 3254, 2106], [3497, 4889, 3254, 909], [4937, 3150, 2511, 3939, 162], [4937, 3150, 2511, 3939, 6222], [6768, 3497, 9297, 3254, 6344], [920, 1692, 9493, 3939]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


In [7]:
import numpy as np


In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0 3497 5757 3254 8472]
 [   0    0    0    0 3497 5757 3254 2106]
 [   0    0    0    0 3497 4889 3254  909]
 [   0    0    0 4937 3150 2511 3939  162]
 [   0    0    0 4937 3150 2511 3939 6222]
 [   0    0    0 6768 3497 9297 3254 6344]
 [   0    0    0    0  920 1692 9493 3939]]


In [9]:
dim=10


In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')


In [11]:
model.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))


[[[-0.0018091   0.03462449 -0.04122971  0.00145536 -0.04358247
   -0.0032903  -0.013011   -0.02780284 -0.03018766  0.02651362]
  [-0.0018091   0.03462449 -0.04122971  0.00145536 -0.04358247
   -0.0032903  -0.013011   -0.02780284 -0.03018766  0.02651362]
  [-0.0018091   0.03462449 -0.04122971  0.00145536 -0.04358247
   -0.0032903  -0.013011   -0.02780284 -0.03018766  0.02651362]
  [-0.0018091   0.03462449 -0.04122971  0.00145536 -0.04358247
   -0.0032903  -0.013011   -0.02780284 -0.03018766  0.02651362]
  [ 0.049153   -0.01667921  0.03500736  0.00672569  0.01934775
   -0.01134453 -0.01534666  0.02106898 -0.02854117  0.0424245 ]
  [-0.02419813 -0.02720275  0.04700602 -0.00407636 -0.01746628
    0.01163917 -0.04142529 -0.00541981 -0.01815943  0.03766063]
  [ 0.00576116 -0.04261519 -0.04738809 -0.03823195  0.00770127
    0.00407844 -0.01268034 -0.03922473 -0.03422334  0.04691378]
  [ 0.03109653 -0.00970274 -0.04370123 -0.02658013 -0.03539059
   -0.04991976  0.03522403 -0.00160839  0.013952

In [13]:
embedded_docs[0]


array([   0,    0,    0,    0, 3497, 5757, 3254, 8472], dtype=int32)

In [14]:
print(model.predict(embedded_docs)[0])


[[-0.0018091   0.03462449 -0.04122971  0.00145536 -0.04358247 -0.0032903
  -0.013011   -0.02780284 -0.03018766  0.02651362]
 [-0.0018091   0.03462449 -0.04122971  0.00145536 -0.04358247 -0.0032903
  -0.013011   -0.02780284 -0.03018766  0.02651362]
 [-0.0018091   0.03462449 -0.04122971  0.00145536 -0.04358247 -0.0032903
  -0.013011   -0.02780284 -0.03018766  0.02651362]
 [-0.0018091   0.03462449 -0.04122971  0.00145536 -0.04358247 -0.0032903
  -0.013011   -0.02780284 -0.03018766  0.02651362]
 [ 0.049153   -0.01667921  0.03500736  0.00672569  0.01934775 -0.01134453
  -0.01534666  0.02106898 -0.02854117  0.0424245 ]
 [-0.02419813 -0.02720275  0.04700602 -0.00407636 -0.01746628  0.01163917
  -0.04142529 -0.00541981 -0.01815943  0.03766063]
 [ 0.00576116 -0.04261519 -0.04738809 -0.03823195  0.00770127  0.00407844
  -0.01268034 -0.03922473 -0.03422334  0.04691378]
 [ 0.03109653 -0.00970274 -0.04370123 -0.02658013 -0.03539059 -0.04991976
   0.03522403 -0.00160839  0.01395271  0.03979773]]
